[workspace]

members= [
    'gu-actix',
    'gu-base',
    'gu-webapp',
	'gu-provider',
	'gu-hub',
	'gu-ethkey',
	'gu-net',
	'gu-persist',
	'gu-lan',
	'gu-hardware',
	'gu-event-bus',
]

[dependencies]
log="0.4"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }

#[patch.'https://github.com/tworec/parity-ethereum']
#ethkey = { path = '../parity-ethereum/ethkey'}
#ethstore = { path = '../parity-ethereum/ethstore'}

[profile.release]
codegen-units = 1
lto=true
