[package]
name = "gu-actix"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.1"
actix = "0.7"
crossbeam-channel="0.3.6"
bytes="0.4"
failure="0.1"
serde="1.0"

[dev-dependencies]
tokio-timer = "0.2.8"

