[package]
name = "gu-base"
version = "0.1.0"

[dependencies]
futures = "0.1"
tokio="0.1"
actix = "0.7"
actix-web = {version= "0.7"}
clap = "2.32"
log="0.4"
env_logger = "0.5"
indicatif = "0.9"
prettytable-rs="0.7"
lazy_static="1.1"
bytes = "0.4.10"
futures-cpupool = "0.1.8"
sha1 = "0.6.0"