[package]
name = "gu-plugin-api"
version = "0.2.0"
authors = ["golemfactory"]
edition = "2018"

[dependencies]
awc="0.2.1"
futures = "0.1.25"
http = "0.1.1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

